---
train:

    params:
        batch_size: 512
        epoch: 80
        lr: 0.0005
        decay: 0.5
        decay_step: 60
        warmup: 5

    save:
        metapath: "D:/PhD/Experiments/gazetr/Transformer-6layers"
        folder: mpii
        model_name: trans6
        step: 10

    data:
        image: "D:/PhD/Datasets/MPIIFaceGaze/images"
        label: "D:/PhD/Datasets/MPIIFaceGaze/labels"
        header: False
        name: mpii
        isFolder: True
        
    pretrain:
        enable: False # True
        path: "D:/PhD/Experiments/gazetr/Transformer-6layers/mpii/checkpoint/Iter_50_trans6.pt"
        device: 0

    device: 0

    reader: reader

# dropout = 0
# dim_feed = 512
